'use strict'

export const OPEN_REGISTER_VIDEO = 'ui:OPEN_REGISTER_VIDEO'
export const CLOSE_REGISTER_VIDEO = 'ui:CLOSE_REGISTER_VIDEO'
export const OPEN_SINGLE_VIDEO = 'ui:OPEN_SINGLE_VIDEO'
export const CLOSE_SINGLE_VIDEO = 'ui:CLOSE_SINGLE_VIDEO'
